### ISSUE TITLE
incompatible with indipets

### ISSUE THREAD

**Issue by wackoamd1** [Safrodev/HoverPets#1]
with indypets u have to shift rightclick your pet to make it follow u , however when i do it with your pet it gives me the item in my inventory , my pet dissapears and i can never summon it again becuase somehow minecraft still thinks is in the world.

ow and since im here anyway , the magma pet doesnt allow me to walk on lava , i burned to a crisp ;-)

**Comment by Safrodev** [comment]
I think I have an idea on how to fix Indypet compatibility but I’m not sure why the magma pet isn’t working. Do you happen to have any error messages or some other mod that may be affecting it? Also are you playing on a server or single player?

Edit: I found that the magma cube pet does allow you to walk on lava, but it doesn't prevent you from taking fire damage while on the lava. I'm going to release a change soon.

**Comment by Safrodev** [comment]
Everything should be fixed and improved in v0.1.1 now :)
