### ISSUE TITLE
Can't dissmiss pet

### ISSUE THREAD

**Issue by arquxx** [Safrodev/HoverPets#2]
I got Magma Cube pet, but I don't know how to dismiss it. Sneaking and right-clicking doesn't do nothing. It also can't be killed.

Fabric 1.18.1

**Comment by Safrodev** [comment]
You have to right-click without sneaking and aim underneath the pet. Let me know if you are still having trouble, and you can kill then with commands if you want.

**Comment by Herbsthase** [comment]
Same problem with Foxpet. Cant dismiss it and don't know how to kill with commands 

Fabric 1.18.1

**Comment by Safrodev** [comment]
Make sure you right-click  _underneath_ the pet and you cannot be sneaking. Also check for other mods that may be conflicting with this like Indypets.

Command: /kill @e[type=hoverpets:**name**_pet]  (This will kill ALL pets of that type)
