### ISSUE TITLE
Ocelot Recipe Makes a Blaze Pet

### ISSUE THREAD

**Issue by bluejunimo** [Safrodev/HoverPets#3]
Crafting a Ocelot Pet w/ cod and gold ingots makes a blaze pet.
Change [line 17](https://github.com/Safrodev/HoverPets/blob/cb63204ab65afdd1e9ad9de83cac908791d464d5/src/main/resources/data/hoverpets/recipes/ocelot_pet.json) to give the paly the ocelot pet instead of the blaze pet

Happy New Year!
Max

**Comment by Safrodev** [comment]
Silly mistake by me (no surprise), I’ll have it fixed in the next release :)
