### ISSUE TITLE
Magma Cube doesn't follow over lava

### ISSUE THREAD

**Issue by nivensd** [Safrodev/HoverPets#6]
As stated, the magma cube doesn't float over lava with you and seems to, after a distance away, no longer give the lava walking ability? I had immunity to the heat still but while running over a lava sea in the nether, it couldn't follow me and I started sinking. Had to hold jump to keep my head above the lava and try to find land to get back onto.

**Comment by Safrodev** [comment]
I’m guessing this is because the magma cube pet can walk on lava, but it doesn’t know how to pathfind on it. I will get it fixed in the next version, sorry for the inconvenience.

**Comment by nivensd** [comment]
No problem. I just found the issue is mostly avoided if I island hop instead of trying to cross the big stretches all at once, since it'll teleport to me once I'm on land. The fix will still be appreciated though, thank you.

**Comment by Safrodev** [comment]
Fixed in 0.3.1
