### ISSUE TITLE
[SUGGESTION] Make Glow Squid Pet a light source

### ISSUE THREAD

**Issue by cowsha** [Safrodev/HoverPets#7]
Just a bit of light for cave exploration

**Comment by Safrodev** [comment]
This was originally planned, but it’s unfortunately not possible without changing Minecraft’s whole lighting engine.  It may be possible to do this with a dynamic lights mod compat, but normally it is not.

**Comment by cowsha** [comment]
LambDynamicLights compatibility?

**Comment by Safrodev** [comment]
Yep

**Comment by Safrodev** [comment]
Added in v0.3.3
